name: netlify-pr-preview
on: [push, pull_request]
jobs:
  netlify:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        id: antora-build
        run: |
           yarn
           ./node_modules/.bin/antora generate antora-playbook.yml
      - name: Publish
        uses: netlify/actions/cli@master
        id: netlify-publish
        with:
          args: deploy --dir=build/site --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         script: |
           const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
           const netlifyUrl = ${{ steps.netlify-publish.outputs.NETLIFY_URL }};
           console.log(`Netlify app deployed at ${netlifyUrl}`);
           const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
           github.issues.createComment({ issue_number, owner, repo, body: `👋  ${netlifyUrl}` });
