#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Publish Doc Content

on:
  workflow_run:
    workflows: ["build-documentation-pr"]
    types:
      - completed

jobs:
  publish:
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - name: download doc artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: doc-content
          path: content
      - name: PR number
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pull-request-number
      - name: Grab pull request number
        run: |
          pr_number=$(cat "PR_NUMBER")
          if ! [[ "$pr_number" =~ ^[0-9]+$ ]]; then
            echo "pr number invalid"
            exit 1
          fi
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
      - name: PR sha
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pull-request-sha
      - name: Grab pull request sha1
        run: |
          pr_sha=$(cat "PR_SHA")
          echo "PR_SHA=$pr_sha" >> $GITHUB_ENV
      - name: Publish
        uses: netlify/actions/cli@master
        id: netlify-publish
        with:
          args: deploy --dir=content --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: 'Comment PR'
        uses: actions/github-script@v3.0.0
        with:
         script: |
           const { repo: { owner, repo } } = context;
           const netlifyUrl = '${{ steps.netlify-publish.outputs.NETLIFY_URL }}';
           await github.repos.createCommitStatus({ owner, repo, sha: process.env.PR_SHA, state: "success", target_url: netlifyUrl, description: "Browse PR documentation online", context: "browse built doc"})
